-- Dev Workbench MySQL 8.0 初始化脚本
-- 应用启动时也会执行 SQLAlchemy create_all；本脚本用于显式初始化数据库。
CREATE DATABASE IF NOT EXISTS workbench CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE workbench;

CREATE TABLE IF NOT EXISTS `user` (
  id INT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(80) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL,
  display_name VARCHAR(120) NOT NULL DEFAULT '管理员', avatar_url VARCHAR(500), token_version INT NOT NULL DEFAULT 1,
  is_active BOOLEAN NOT NULL DEFAULT TRUE, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS todo_task (
  id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, parent_id INT NULL, title VARCHAR(240) NOT NULL, description TEXT, notes TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'todo', priority VARCHAR(20) NOT NULL DEFAULT 'medium', due_at DATETIME NULL, group_name VARCHAR(80) NOT NULL DEFAULT '默认分组',
  tags JSON, archived BOOLEAN NOT NULL DEFAULT FALSE, position INT NOT NULL DEFAULT 0, completed_at DATETIME NULL, timer_started_at DATETIME NULL, elapsed_seconds INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX(user_id), INDEX(status), INDEX(archived), CONSTRAINT fk_todo_user FOREIGN KEY(user_id) REFERENCES `user`(id) ON DELETE CASCADE,
  CONSTRAINT fk_todo_parent FOREIGN KEY(parent_id) REFERENCES todo_task(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS work_record (
  id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, title VARCHAR(200) NOT NULL, content TEXT, work_date DATE NOT NULL, hours DECIMAL(6,2) NOT NULL DEFAULT 0, tags JSON, task_id INT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(user_id), INDEX(work_date),
  CONSTRAINT fk_record_user FOREIGN KEY(user_id) REFERENCES `user`(id) ON DELETE CASCADE, CONSTRAINT fk_record_task FOREIGN KEY(task_id) REFERENCES todo_task(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS work_plan (
  id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, title VARCHAR(200) NOT NULL, description TEXT, start_date DATE NOT NULL, end_date DATE NOT NULL,
  priority VARCHAR(20) NOT NULL DEFAULT 'medium', status VARCHAR(20) NOT NULL DEFAULT 'pending', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX(user_id), CONSTRAINT fk_plan_user FOREIGN KEY(user_id) REFERENCES `user`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS event_reminder (
  id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, title VARCHAR(200) NOT NULL, content TEXT, remind_at DATETIME NOT NULL, repeat_type VARCHAR(20) NOT NULL DEFAULT 'once', status VARCHAR(20) NOT NULL DEFAULT 'active', snoozed_until DATETIME NULL,
  schedule_type VARCHAR(20) NOT NULL DEFAULT 'once', time_of_day VARCHAR(8) NULL, weekdays JSON NULL, month_days JSON NULL, next_trigger_at DATETIME NULL, last_trigger_at DATETIME NULL, timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(user_id), INDEX(remind_at),
  CONSTRAINT fk_reminder_user FOREIGN KEY(user_id) REFERENCES `user`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS todo_subtask (
  id INT PRIMARY KEY AUTO_INCREMENT, task_id INT NOT NULL, title VARCHAR(240) NOT NULL, completed BOOLEAN NOT NULL DEFAULT FALSE, INDEX(task_id),
  CONSTRAINT fk_subtask_task FOREIGN KEY(task_id) REFERENCES todo_task(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS quick_link (
  id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, title VARCHAR(120) NOT NULL, url VARCHAR(1000) NOT NULL, category VARCHAR(80) NOT NULL DEFAULT '未分类', description VARCHAR(500), position INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(user_id),
  CONSTRAINT fk_link_user FOREIGN KEY(user_id) REFERENCES `user`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS tool_usage_log (
  id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, tool_name VARCHAR(80) NOT NULL, action VARCHAR(80) NOT NULL DEFAULT 'use', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX(user_id), INDEX(tool_name),
  CONSTRAINT fk_tool_user FOREIGN KEY(user_id) REFERENCES `user`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS account_category (
  id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, name VARCHAR(80) NOT NULL,
  entry_type VARCHAR(20) NOT NULL DEFAULT 'expense', is_default BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX(user_id), INDEX(entry_type), CONSTRAINT fk_account_category_user FOREIGN KEY(user_id) REFERENCES `user`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS account_entry (
  id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, entry_type VARCHAR(20) NOT NULL,
  amount DECIMAL(12,2) NOT NULL, category VARCHAR(80) NOT NULL, note TEXT, entry_date DATE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX(user_id), INDEX(entry_type), INDEX(entry_date), CONSTRAINT fk_account_entry_user FOREIGN KEY(user_id) REFERENCES `user`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS memo (
  id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, title VARCHAR(200) NOT NULL, content TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX(user_id), INDEX(created_at), CONSTRAINT fk_memo_user FOREIGN KEY(user_id) REFERENCES `user`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS system_config (
  id INT PRIMARY KEY AUTO_INCREMENT, user_id INT NOT NULL, config_key VARCHAR(100) NOT NULL, config_value JSON, INDEX(user_id), INDEX(config_key),
  CONSTRAINT fk_config_user FOREIGN KEY(user_id) REFERENCES `user`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
