<template>
  <div class="page-heading"><div><h1>{{ greeting }}，{{ app.user?.display_name || '管理员' }} <span class="wave">✦</span></h1><p>这是你的个人工作节奏，专注于今天最重要的事情。</p></div><div class="page-actions"><el-button class="soft-button" @click="$router.push('/records')">+ 记录工作</el-button><el-button type="primary" @click="$router.push('/todos')">+ 新建待办</el-button></div></div>
  <div class="stats-grid"><StatCard label="本月工时" :value="`${stats.cards.hours}h`" foot="累计工作时长" :trend="8" icon="◷" tone="purple" /><StatCard label="待办完成率" :value="`${stats.cards.completion_rate}%`" foot="保持稳定的推进节奏" :trend="12" icon="✓" tone="green" /><StatCard label="进行中任务" :value="stats.cards.todo_total - stats.cards.todo_done" foot="还有空间继续推进" icon="↗" tone="orange" /><StatCard label="今日专注" :value="focusTasks.length ? formatDuration(focusTasks[0].elapsed_seconds) : '—'" :foot="focusTasks.length ? focusTasks[0].title : '启动一个计时任务'" icon="◉" tone="red" /></div>
  <div class="panel focus-panel"><div class="panel-header"><div><div class="panel-title">正在专注</div><div class="panel-subtitle">所有正在计时的任务</div></div><el-button text @click="$router.push('/todos')">打开 Todo →</el-button></div><div v-if="focusTasks.length" class="focus-list"><button v-for="task in focusTasks" :key="task.id" class="focus-item" type="button" @click="$router.push('/todos')"><span class="focus-pulse" /><span class="focus-content"><b>{{ task.title }}</b><small>{{ statusMap[task.status] || task.status }}</small></span><strong>{{ formatDuration(task.elapsed_seconds) }}</strong></button></div><el-empty v-else description="当前没有正在计时的任务" :image-size="55" /></div>
  <div class="grid-2"><div class="panel"><div class="panel-header"><div><div class="panel-title">工作量趋势</div><div class="panel-subtitle">本月每日投入时间</div></div><el-button text @click="$router.push('/records')">查看记录 →</el-button></div><div ref="lineRef" class="chart"></div></div><div class="panel"><div class="panel-header"><div><div class="panel-title">待办完成情况</div><div class="panel-subtitle">当前未归档任务</div></div><el-button text @click="$router.push('/todos')">打开看板 →</el-button></div><div ref="pieRef" class="chart"></div></div></div>
  <div class="grid-2" style="margin-top:18px"><div class="panel"><div class="panel-header"><div><div class="panel-title">今日工作记录</div><div class="panel-subtitle">把过程变成可回看的资产</div></div><el-button text @click="$router.push('/records')">全部记录 →</el-button></div><div class="mini-list"><div v-for="item in recentRecords" :key="item.id" class="mini-item"><span class="dot"></span><div class="mini-content"><b>{{ item.title }}</b><span>{{ item.work_date }} · {{ formatWorkHours(item.hours) }}</span></div><span class="status-tag">{{ item.tags?.[0] || '工作' }}</span></div><el-empty v-if="!recentRecords.length" description="还没有今日记录" :image-size="55" /></div></div><div class="panel"><div class="panel-header"><div><div class="panel-title">工具使用频次</div><div class="panel-subtitle">最近使用的开发工具</div></div><el-button text @click="$router.push('/toolkit')">打开工具箱 →</el-button></div><div ref="barRef" class="chart"></div></div></div>
</template>
<script setup>
import { computed, nextTick, onMounted, onUnmounted, ref, watch } from 'vue'; import * as echarts from 'echarts'; import { useAppStore } from '../stores'; import { api } from '../api/http'; import StatCard from '../components/StatCard.vue'
const app = useAppStore(); const greeting = ref(''); const focusTick = ref(Date.now()); const stats = ref({ cards: { hours: 0, completion_rate: 0, todo_total: 0, todo_done: 0 }, focus_tasks: [], work_trend: [], tool_usage: [] }); const recentRecords = ref([]); const lineRef = ref(); const pieRef = ref(); const barRef = ref(); let charts = []; let greetingTimer; let focusTimer
const statusMap = { todo: '待处理', doing: '进行中', done: '已完成' }
const focusTasks = computed(() => { const now = focusTick.value; return (stats.value.focus_tasks || []).map(task => ({ ...task, elapsed_seconds: task.elapsed_seconds + (task.timer_started_at ? Math.max(0, Math.floor((now - new Date(task.timer_started_at).getTime()) / 1000)) : 0) })) })
function formatDuration(seconds) { const total = Math.max(0, Number(seconds) || 0); const hours = Math.floor(total / 3600); const minutes = Math.floor((total % 3600) / 60); const secs = total % 60; return hours ? `${hours}小时 ${String(minutes).padStart(2, '0')}分` : `${String(minutes).padStart(2, '0')}:${String(secs).padStart(2, '0')}` }
function formatWorkHours(value) { const totalMinutes = Math.max(0, Math.round(Number(value || 0) * 60)); const hours = Math.floor(totalMinutes / 60); const minutes = totalMinutes % 60; if (hours) return minutes ? `${hours}小时${minutes}分` : `${hours}小时`; return `${minutes}分` }
const colors = () => ({ text: getComputedStyle(document.documentElement).getPropertyValue('--muted'), line: getComputedStyle(document.documentElement).getPropertyValue('--line'), primary: getComputedStyle(document.documentElement).getPropertyValue('--primary'), primaryStrong: getComputedStyle(document.documentElement).getPropertyValue('--primary-strong'), primarySoft: getComputedStyle(document.documentElement).getPropertyValue('--primary-soft'), accent: getComputedStyle(document.documentElement).getPropertyValue('--accent'), green: getComputedStyle(document.documentElement).getPropertyValue('--green') })
function updateGreeting() { const hour = new Date().getHours(); greeting.value = hour < 6 || hour >= 22 ? '夜深了' : hour < 9 ? '早上好' : hour < 12 ? '上午好' : hour < 14 ? '中午好' : hour < 18 ? '下午好' : '晚上好' }
function render() { charts.forEach(c => c.dispose()); charts = []; const c = colors(); const line = echarts.init(lineRef.value); line.setOption({ grid:{left:8,right:8,top:20,bottom:8,containLabel:true}, xAxis:{type:'category',boundaryGap:false,data:stats.value.work_trend.map(x=>x.date.slice(5)),axisLabel:{color:c.text,fontSize:10},axisLine:{lineStyle:{color:c.line}}}, yAxis:{type:'value',axisLabel:{color:c.text,fontSize:10},splitLine:{lineStyle:{color:c.line}}}, series:[{data:stats.value.work_trend.map(x=>x.hours),type:'line',smooth:true,symbol:'none',lineStyle:{color:c.primary,width:3},areaStyle:{color:c.primarySoft}}] }); const pie = echarts.init(pieRef.value); pie.setOption({ tooltip:{trigger:'item'}, series:[{type:'pie',radius:['56%','76%'],center:['50%','50%'],label:{show:false},data:[{value:stats.value.cards.todo_done,name:'已完成',itemStyle:{color:c.green}},{value:Math.max(0,stats.value.cards.todo_total-stats.value.cards.todo_done),name:'待推进',itemStyle:{color:c.accent}}]}] }); const bar = echarts.init(barRef.value); bar.setOption({grid:{left:8,right:8,top:20,bottom:8,containLabel:true},xAxis:{type:'category',data:stats.value.tool_usage.map(x=>x.name),axisLabel:{color:c.text,fontSize:10},axisLine:{lineStyle:{color:c.line}}},yAxis:{type:'value',axisLabel:{color:c.text,fontSize:10},splitLine:{lineStyle:{color:c.line}}},series:[{type:'bar',barWidth:18,data:stats.value.tool_usage.map(x=>x.count),itemStyle:{borderRadius:[5,5,0,0],color:c.primaryStrong}}]}); charts=[line,pie,bar] }
onMounted(async () => { updateGreeting(); greetingTimer = window.setInterval(updateGreeting, 60000); focusTimer = window.setInterval(() => { focusTick.value = Date.now() }, 1000); const [dash, records] = await Promise.all([api.dashboard(), api.records({ start: new Date().toISOString().slice(0,10), end: new Date().toISOString().slice(0,10) })]); stats.value = dash.data; recentRecords.value = records.data.slice(0, 4); await nextTick(); render(); window.addEventListener('resize', () => charts.forEach(c => c.resize())) })
onUnmounted(() => { window.clearInterval(greetingTimer); window.clearInterval(focusTimer) })
watch(() => [app.theme, app.accentTheme], async () => { await nextTick(); if (lineRef.value) render() })
</script>
