<template>
  <div class="login-page"><div class="login-grid"></div><div class="login-brand"><div class="brand-mark large">⌘</div><div><b>Workbench</b><span>个人效率操作系统</span></div></div><div class="login-card"><div class="login-kicker">WELCOME BACK</div><h1>把注意力留给<br /><em>真正重要的事</em></h1><p class="login-intro">记录、计划、执行与复盘，都在这里形成自己的工作节奏。</p><el-form :model="form" @submit.prevent="submit"><el-form-item><el-input v-model="form.username" size="large" placeholder="用户名" :prefix-icon="User" /></el-form-item><el-form-item><el-input v-model="form.password" size="large" type="password" show-password placeholder="密码" :prefix-icon="Lock" @keyup.enter="submit" /></el-form-item><el-button type="primary" size="large" class="login-button" :loading="loading" @click="submit">进入工作台 <el-icon><Right /></el-icon></el-button></el-form><div class="login-secure-note"><span class="secure-dot"></span>本地私有工作台 · 数据保存在你的数据库中</div></div><div class="login-footer">LOCAL · PRIVATE · FOCUSED <span>v1.0.0</span></div></div>
</template>
<script setup>
import { reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import { ElMessage } from 'element-plus'; import { User, Lock, Right } from '@element-plus/icons-vue'; import { api } from '../api/http'; import { useAppStore } from '../stores'
const form = reactive({ username: '', password: '' }); const loading = ref(false); const router = useRouter(); const app = useAppStore()
function pemToArrayBuffer(pem) { const base64 = pem.replace(/-----(BEGIN|END) PUBLIC KEY-----/g, '').replace(/\s/g, ''); const binary = atob(base64); const bytes = new Uint8Array(binary.length); for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index); return bytes.buffer }
async function encryptPassword(password, pem) { const key = await window.crypto.subtle.importKey('spki', pemToArrayBuffer(pem), { name: 'RSA-OAEP', hash: 'SHA-256' }, false, ['encrypt']); const encrypted = await window.crypto.subtle.encrypt({ name: 'RSA-OAEP' }, key, new TextEncoder().encode(password)); const bytes = new Uint8Array(encrypted); let binary = ''; bytes.forEach(byte => { binary += String.fromCharCode(byte) }); return btoa(binary) }
async function submit() { if (!form.username || !form.password) return ElMessage.warning('请输入用户名和密码'); loading.value = true; try { const keyRes = await api.loginPublicKey(); const encryptedPassword = await encryptPassword(form.password, keyRes.data.public_key); const res = await api.login({ username: form.username, encrypted_password: encryptedPassword }); app.setSession(res.data); router.push('/dashboard'); ElMessage.success('欢迎回来') } finally { loading.value = false } }
</script>
