<template>
  <div class="login-page"><div class="login-grid"></div><button class="login-theme-toggle" :title="app.accentTheme === 'indigo' ? '切换到天蓝青绿' : '切换到蓝紫品牌'" :aria-label="app.accentTheme === 'indigo' ? '切换到天蓝青绿主题' : '切换到蓝紫品牌主题'" @click="app.toggleAccentTheme()"><span :class="['accent-swatch', app.accentTheme]" /><span>{{ app.accentTheme === 'indigo' ? '天蓝青绿' : '蓝紫品牌' }}</span></button><div class="login-layout"><section class="login-hero"><div class="login-brand"><div class="brand-mark large">⌘</div><div><b>Workbench</b><span>个人效率操作系统</span></div></div><div class="login-kicker">WELCOME BACK</div><h1>把注意力留给<br /><em>真正重要的事</em></h1><p class="login-intro">记录、计划、执行与复盘，都在这里形成自己的工作节奏。</p><div class="login-traits">LOCAL <i /> PRIVATE <i /> FOCUSED</div></section><section class="login-card"><h2>登录工作台</h2><p class="login-card-subtitle">验证身份以继续您的心流时间</p><el-form :model="form" @submit.prevent="submit"><el-form-item label="用户名" :class="{ 'is-error': formError && !form.username }"><el-input v-model="form.username" size="large" placeholder="请输入账号" autocomplete="username" :prefix-icon="User" :aria-invalid="Boolean(formError && !form.username)" @input="clearFormError" /></el-form-item><el-form-item label="密码" :class="{ 'is-error': formError && !form.password }"><el-input v-model="form.password" size="large" type="password" show-password placeholder="••••••••" autocomplete="current-password" :prefix-icon="Lock" :aria-invalid="Boolean(formError && !form.password)" @input="clearFormError" @keyup.enter="submit" /></el-form-item><div class="login-form-options"><el-checkbox>记住我</el-checkbox><a href="#forgot-password">忘记密码?</a></div><div v-if="formError" class="login-form-error" role="alert"><el-icon><WarningFilled /></el-icon><span>{{ formError }}</span></div><el-button type="primary" size="large" class="login-button" :loading="loading" @click="submit">进入工作台 <el-icon><Right /></el-icon></el-button></el-form><div class="login-secure-note"><span class="secure-dot" />本地加密连接 · 仅用于当前工作台</div><div class="login-card-footer"><span>v1.0.0</span><span>帮助中心</span><span>隐私政策</span></div></section></div><div class="login-footer">LOCAL · PRIVATE · FOCUSED <span>v1.0.0</span></div></div>
</template>
<script setup>
import { reactive, ref } from 'vue'; import { useRouter } from 'vue-router'; import { ElMessage } from 'element-plus'; import { User, Lock, Right, WarningFilled } from '@element-plus/icons-vue'; import { api } from '../api/http'; import { useAppStore } from '../stores'; import { encryptPassword } from '../utils/rsa'
const form = reactive({ username: '', password: '' }); const loading = ref(false); const formError = ref(''); const router = useRouter(); const app = useAppStore()
function clearFormError() { formError.value = '' }
async function submit() { formError.value = ''; if (!form.username || !form.password) { formError.value = '请输入用户名和密码'; ElMessage.warning(formError.value); return } loading.value = true; try { const keyRes = await api.loginPublicKey(); const encryptedPassword = await encryptPassword(form.password, keyRes.data.public_key); const res = await api.login({ username: form.username, encrypted_password: encryptedPassword }); app.setSession(res.data); router.push('/dashboard'); ElMessage.success('欢迎回来') } catch (error) { formError.value = error?.message || '登录失败，请稍后重试'; ElMessage.error(formError.value) } finally { loading.value = false } }
</script>
