<template>
  <div v-if="dashboard?.project" class="project-detail-page">
    <div class="page-heading"><div><div class="back-link" @click="router.push('/projects')">← 返回项目</div><h1>{{ dashboard.project.name }}</h1><p>{{ dashboard.project.description || '项目详情与推进仪表盘' }}</p></div><el-button @click="router.push('/todos')">查看项目 Todo</el-button></div>
    <div class="project-detail-meta"><el-tag :type="statusType(dashboard.project.status)">{{ statusMap[dashboard.project.status] || dashboard.project.status }}</el-tag><span v-if="dashboard.project.due_date">截止 {{ dashboard.project.due_date }}</span><a v-if="dashboard.project.repo_url" :href="dashboard.project.repo_url" target="_blank" rel="noreferrer">代码仓库 ↗</a><a v-if="dashboard.project.deployment_url" :href="dashboard.project.deployment_url" target="_blank" rel="noreferrer">部署地址 ↗</a></div>
    <div class="metric-grid project-metrics"><div class="metric-card"><span>完成进度</span><strong>{{ dashboard.cards.completion_rate }}%</strong><el-progress :percentage="dashboard.cards.completion_rate" :show-text="false" /></div><div class="metric-card"><span>投入工时</span><strong>{{ formatHours(dashboard.cards.hours) }}</strong><small>累计工作记录</small></div><div class="metric-card"><span>未完成任务</span><strong>{{ dashboard.cards.todo_total - dashboard.cards.todo_done }}</strong><small>共 {{ dashboard.cards.todo_total }} 项 Todo</small></div><div class="metric-card"><span>逾期任务</span><strong>{{ dashboard.cards.overdue }}</strong><small>需要优先处理</small></div></div>
    <div class="project-info-grid"><section class="table-card project-info-card"><div class="section-heading"><h2>项目目标</h2></div><p class="project-goal">{{ dashboard.project.goal || '还没有填写项目目标。' }}</p><div v-if="dashboard.project.tech_stack?.length" class="tag-row"><el-tag v-for="tech in dashboard.project.tech_stack" :key="tech" size="small" effect="plain">{{ tech }}</el-tag></div><div v-if="dashboard.project.tags?.length" class="tag-row"><el-tag v-for="tag in dashboard.project.tags" :key="tag" size="small" type="info" effect="plain"># {{ tag }}</el-tag></div><p v-if="dashboard.project.local_path" class="muted-text project-path">本地目录：{{ dashboard.project.local_path }}</p></section><section class="table-card project-info-card"><div class="section-heading"><h2>里程碑</h2><el-button link type="primary" @click="openMilestone">+ 添加</el-button></div><div v-for="item in dashboard.milestones" :key="item.id" class="project-list-row"><div><b>{{ item.title }}</b><small>{{ item.due_date || '未设置日期' }}</small></div><div class="row-actions"><el-tag size="small" :type="milestoneType(item.status)">{{ milestoneMap[item.status] }}</el-tag><el-button link type="danger" @click="removeMilestone(item.id)">删除</el-button></div></div><el-empty v-if="!dashboard.milestones.length" description="暂无里程碑" :image-size="48" /></section></div>
    <div class="project-info-grid"><section class="table-card project-info-card"><div class="section-heading"><h2>版本</h2><el-button link type="primary" @click="openVersion">+ 添加</el-button></div><div v-for="item in dashboard.versions" :key="item.id" class="project-list-row"><div><b>{{ item.version }}</b><small>{{ item.target_date || '未设置目标日期' }}</small></div><div class="row-actions"><el-tag size="small" :type="versionType(item.status)">{{ versionMap[item.status] }}</el-tag><el-button link type="danger" @click="removeVersion(item.id)">删除</el-button></div></div><el-empty v-if="!dashboard.versions.length" description="暂无版本" :image-size="48" /></section><section class="table-card project-info-card"><div class="section-heading"><h2>最近提交</h2><el-button link type="primary" @click="openCommit">+ 添加</el-button></div><div v-for="item in dashboard.recent_commits" :key="item.id" class="project-list-row"><div><b>{{ item.message }}</b><small>{{ item.commit_hash }} · {{ item.committed_at || '未设置时间' }}</small></div><el-button link type="danger" @click="removeCommit(item.id)">删除</el-button></div><el-empty v-if="!dashboard.recent_commits.length" description="暂无提交记录" :image-size="48" /></section></div>
    <section class="table-card project-info-card"><div class="section-heading"><h2>最近工作记录</h2><el-button link type="primary" @click="router.push('/records')">查看全部 →</el-button></div><el-table :data="dashboard.recent_records" stripe><el-table-column prop="work_date" label="日期" width="130" /><el-table-column prop="title" label="记录" min-width="220" /><el-table-column label="工时" width="120"><template #default="scope">{{ formatHours(scope.row.hours) }}</template></el-table-column></el-table><el-empty v-if="!dashboard.recent_records.length" description="暂无工作记录" /></section>
  </div>
  <el-empty v-else-if="loading" description="正在加载项目…" />
  <el-result v-else-if="loadError" icon="error" title="项目详情加载失败" :sub-title="loadError"><template #extra><el-button type="primary" @click="load">重新加载</el-button></template></el-result>
  <el-empty v-else description="项目不存在或暂无数据" />

  <el-dialog v-model="milestoneDialog" title="添加里程碑" width="520px"><el-form :model="milestoneForm" label-width="80px"><el-form-item label="名称"><el-input v-model="milestoneForm.title" /></el-form-item><el-form-item label="状态"><el-select v-model="milestoneForm.status"><el-option v-for="(label, value) in milestoneMap" :key="value" :label="label" :value="value" /></el-select></el-form-item><el-form-item label="截止日期"><el-date-picker v-model="milestoneForm.due_date" value-format="YYYY-MM-DD" clearable /></el-form-item><el-form-item label="说明"><el-input v-model="milestoneForm.description" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="milestoneDialog=false">取消</el-button><el-button type="primary" @click="saveMilestone">保存</el-button></template></el-dialog>
  <el-dialog v-model="versionDialog" title="添加版本" width="520px"><el-form :model="versionForm" label-width="80px"><el-form-item label="版本号"><el-input v-model="versionForm.version" placeholder="例如 v1.0.0" /></el-form-item><el-form-item label="状态"><el-select v-model="versionForm.status"><el-option v-for="(label, value) in versionMap" :key="value" :label="label" :value="value" /></el-select></el-form-item><el-form-item label="目标日期"><el-date-picker v-model="versionForm.target_date" value-format="YYYY-MM-DD" clearable /></el-form-item><el-form-item label="发布说明"><el-input v-model="versionForm.release_notes" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="versionDialog=false">取消</el-button><el-button type="primary" @click="saveVersion">保存</el-button></template></el-dialog>
  <el-dialog v-model="commitDialog" title="添加提交记录" width="520px"><el-form :model="commitForm" label-width="80px"><el-form-item label="提交信息"><el-input v-model="commitForm.message" /></el-form-item><el-form-item label="Commit Hash"><el-input v-model="commitForm.commit_hash" /></el-form-item><div class="two-col"><el-form-item label="分支"><el-input v-model="commitForm.branch" /></el-form-item><el-form-item label="提交时间"><el-date-picker v-model="commitForm.committed_at" type="datetime" value-format="YYYY-MM-DDTHH:mm:ss" clearable /></el-form-item></div><el-form-item label="链接"><el-input v-model="commitForm.url" /></el-form-item></el-form><template #footer><el-button @click="commitDialog=false">取消</el-button><el-button type="primary" @click="saveCommit">保存</el-button></template></el-dialog>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useRoute, useRouter } from 'vue-router'
import { api } from '../api/http'

const route = useRoute(); const router = useRouter(); const projectId = Number(route.params.id); const dashboard = ref(null); const loading = ref(true); const loadError = ref(''); const milestoneDialog = ref(false); const versionDialog = ref(false); const commitDialog = ref(false)
const statusMap = { planning: '规划中', active: '进行中', paused: '已暂停', completed: '已完成', archived: '已归档' }; const milestoneMap = { pending: '待开始', doing: '进行中', done: '已完成' }; const versionMap = { planned: '计划中', active: '开发中', released: '已发布', cancelled: '已取消' }
const milestoneForm = reactive({ title: '', description: '', status: 'pending', due_date: null, position: 0 }); const versionForm = reactive({ version: '', status: 'planned', target_date: null, release_notes: '' }); const commitForm = reactive({ commit_hash: '', message: '', branch: 'main', committed_at: new Date().toISOString().slice(0, 19), url: '' })
function statusType(status) { return { active: 'success', completed: 'success', paused: 'warning', archived: 'info' }[status] || '' }; function milestoneType(status) { return status === 'done' ? 'success' : status === 'doing' ? 'warning' : 'info' }; function versionType(status) { return status === 'released' ? 'success' : status === 'cancelled' ? 'info' : 'warning' }
function formatHours(value) { const minutes = Math.round(Number(value || 0) * 60); return minutes < 60 ? `${minutes}分` : `${Math.floor(minutes / 60)}小时${minutes % 60 ? `${minutes % 60}分` : ''}` }
async function load() { loading.value = true; loadError.value = ''; try { const response = await api.projectDashboard(projectId); dashboard.value = response?.data || null; if (!dashboard.value?.project) loadError.value = '接口返回的数据不完整' } catch (error) { dashboard.value = null; loadError.value = error?.response?.data?.msg || error?.message || '请稍后重试' } finally { loading.value = false } }
function openMilestone() { Object.assign(milestoneForm, { title: '', description: '', status: 'pending', due_date: null, position: dashboard.value?.milestones?.length || 0 }); milestoneDialog.value = true }; function openVersion() { Object.assign(versionForm, { version: '', status: 'planned', target_date: null, release_notes: '' }); versionDialog.value = true }; function openCommit() { Object.assign(commitForm, { commit_hash: '', message: '', branch: 'main', committed_at: new Date().toISOString().slice(0, 19), url: '' }); commitDialog.value = true }
async function saveMilestone() { if (!milestoneForm.title.trim()) return ElMessage.warning('请填写里程碑名称'); await api.createMilestone(projectId, milestoneForm); milestoneDialog.value = false; await load(); ElMessage.success('里程碑已添加') }; async function saveVersion() { if (!versionForm.version.trim()) return ElMessage.warning('请填写版本号'); await api.createVersion(projectId, versionForm); versionDialog.value = false; await load(); ElMessage.success('版本已添加') }; async function saveCommit() { if (!commitForm.message.trim()) return ElMessage.warning('请填写提交信息'); await api.createCommit(projectId, commitForm); commitDialog.value = false; await load(); ElMessage.success('提交记录已添加') }
async function removeMilestone(id) { await ElMessageBox.confirm('确定删除这个里程碑吗？', '删除确认', { type: 'warning' }); await api.deleteMilestone(projectId, id); await load() }; async function removeVersion(id) { await ElMessageBox.confirm('确定删除这个版本吗？', '删除确认', { type: 'warning' }); await api.deleteVersion(projectId, id); await load() }; async function removeCommit(id) { await ElMessageBox.confirm('确定删除这条提交记录吗？', '删除确认', { type: 'warning' }); await api.deleteCommit(projectId, id); await load() }
onMounted(() => load().catch(() => {}))
</script>
