<template>
  <div class="page-heading"><div><h1>工作记录</h1><p>记录完成了什么，也记录为什么值得完成。</p></div><el-button type="primary" @click="openCreate">+ 新增记录</el-button></div>
  <div class="toolbar"><div class="toolbar-left"><el-date-picker v-model="dateRange" type="daterange" value-format="YYYY-MM-DD" range-separator="至" start-placeholder="开始日期" end-placeholder="结束日期" @change="load" /><el-input v-model="keyword" clearable placeholder="检索标题或内容" style="width:220px" @keyup.enter="load"><template #prefix><el-icon><Search /></el-icon></template></el-input></div><div class="toolbar-right"><el-radio-group v-model="view" size="small"><el-radio-button label="list">列表</el-radio-button><el-radio-button label="calendar">日历</el-radio-button></el-radio-group><el-button @click="exportText">导出日报</el-button></div></div>
  <div v-if="view === 'list'">
    <div class="desktop-table table-card"><el-table :data="rows" stripe><el-table-column prop="work_date" label="日期" width="125" /><el-table-column prop="title" label="工作内容" min-width="220" /><el-table-column prop="content" label="复盘备注" min-width="260" show-overflow-tooltip /><el-table-column label="标签" width="190"><template #default="scope"><el-tag v-for="tag in scope.row.tags || []" :key="tag" size="small" effect="plain" style="margin-right:5px">{{ tag }}</el-tag></template></el-table-column><el-table-column prop="hours" label="工时" width="100"><template #default="scope">{{ formatHours(scope.row.hours) }}</template></el-table-column><el-table-column label="操作" width="150" fixed="right"><template #default="scope"><el-button link type="primary" @click="openEdit(scope.row)">编辑</el-button><el-popconfirm title="确认删除这条记录？" @confirm="remove(scope.row.id)"><template #reference><el-button link type="danger">删除</el-button></template></el-popconfirm></template></el-table-column></el-table><el-empty v-if="!rows.length" description="还没有工作记录，今天就从一条开始" /></div>
    <div class="mobile-card-list">
      <article v-for="row in rows" :key="row.id" class="mobile-record-card mobile-content-card">
        <div class="mobile-card-meta"><span>{{ row.work_date }}</span><span>{{ formatHours(row.hours) }}</span></div>
        <h3>{{ row.title }}</h3>
        <p v-if="row.content" class="mobile-card-description">{{ row.content }}</p>
        <div v-if="row.tags?.length" class="mobile-card-tags"><el-tag v-for="tag in row.tags" :key="tag" size="small" effect="plain">{{ tag }}</el-tag></div>
        <div class="mobile-card-actions"><el-button link type="primary" @click="openEdit(row)">编辑</el-button><el-popconfirm title="确认删除这条记录？" @confirm="remove(row.id)"><template #reference><el-button link type="danger">删除</el-button></template></el-popconfirm></div>
      </article>
      <el-empty v-if="!rows.length" description="还没有工作记录，今天就从一条开始" />
    </div>
  </div>
  <div v-else class="panel calendar-placeholder"><el-calendar v-model="calendarDate"><template #date-cell="{ data }"><div class="calendar-day"><span>{{ data.day.split('-').slice(2).join('') }}</span><i v-if="rows.some(x => x.work_date === data.day)"></i></div></template></el-calendar></div>
  <el-dialog v-model="dialog" :title="editing ? '编辑工作记录' : '新增工作记录'" width="560px"><el-form :model="form" label-width="75px"><el-form-item label="工作日期"><el-date-picker v-model="form.work_date" value-format="YYYY-MM-DD" style="width:100%" /></el-form-item><el-form-item label="工作标题"><el-input v-model="form.title" placeholder="例如：完成登录鉴权模块" /></el-form-item><el-form-item label="工作内容"><el-input v-model="form.content" type="textarea" :rows="4" placeholder="记录关键产出、遇到的问题与下一步" /></el-form-item><div class="two-col"><el-form-item label="工时"><el-input-number v-model="form.hours" :min="0" :max="24" :step="0.5" /></el-form-item><el-form-item label="标签"><el-select v-model="form.tags" multiple allow-create filterable style="width:100%"><el-option v-for="tag in ['开发','会议','复盘','学习']" :key="tag" :label="tag" :value="tag" /></el-select></el-form-item></div></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存记录</el-button></template></el-dialog>
</template>
<script setup>
import { reactive, ref, onMounted } from 'vue'; import { ElMessage } from 'element-plus'; import { Search } from '@element-plus/icons-vue'; import { api } from '../api/http'
const rows=ref([]), dateRange=ref([]), keyword=ref(''), view=ref('list'), dialog=ref(false), editing=ref(null), calendarDate=ref(new Date()); const form=reactive({ title:'',content:'',work_date:new Date().toISOString().slice(0,10),hours:1,tags:[] })
async function load(){ const res=await api.records({ start:dateRange.value?.[0], end:dateRange.value?.[1], keyword:keyword.value }); rows.value=res.data }
function openCreate(){ editing.value=null; Object.assign(form,{title:'',content:'',work_date:new Date().toISOString().slice(0,10),hours:1,tags:[]}); dialog.value=true } function openEdit(row){ editing.value=row.id; Object.assign(form,{...row,tags:row.tags||[]}); dialog.value=true }
async function save(){ if(!form.title) return ElMessage.warning('请填写工作标题'); editing.value ? await api.updateRecord(editing.value,form) : await api.record(form); dialog.value=false; ElMessage.success('已保存'); load() } async function remove(id){ await api.deleteRecord(id); ElMessage.success('已删除'); load() }
function formatHours(value){ const totalMinutes=Math.max(0,Math.round(Number(value||0)*60)); const hours=Math.floor(totalMinutes/60); const minutes=totalMinutes%60; if(hours) return minutes ? `${hours}小时${minutes}分` : `${hours}小时`; return `${minutes}分` }
function exportText(){ const text=rows.value.map(x=>`## ${x.work_date} ${x.title}\n${x.content}\n工时：${formatHours(x.hours)}`).join('\n\n'); const blob=new Blob([text],{type:'text/plain;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='工作日报.md'; a.click(); URL.revokeObjectURL(a.href) }
onMounted(load)
</script>
